name: Publish Docker image
on:
  push:
    branches:
      '**'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
          path: packages/cli
          tags: latest
