name: Build
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master
jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ${{matrix.dir}}
    strategy:
      fail-fast: false
      matrix:
        deno: [ '1.7.5', '1.7.0' ]
        dir: ['packages/cli', 'packages/debug']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{matrix.deno}}
      - run: |
          deno --version
          pwd
#      - run: |
#          mkdir dist && deno bundle src/main.ts dist/main.js
#          deno run --allow-run --allow-read --allow-write https://raw.githubusercontent.com/danielr1996/bumpup-deno/feature/ci/packages/cli/src/main.ts
#          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
#          echo ${{ env.VERSION }}
#      - uses: stefanzweifel/git-auto-commit-action@v4
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.VERSION }}
#          release_name: ${{ env.VERSION }}
#          draft: false
#          prerelease: true
#      - run: |
#          ls -la
#          ls -la dist
#      - name: Upload Release Asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./packages/cli/dist/main.js
#          asset_name: main.js
#          asset_content_type: application/javascript
